import Head from "next/head";

const posts = [
  { title: "React Testing", excerpt: "Learn React Testing", id: 1 },
  { title: "React with Tailwind", excerpt: "Learn React with Tailwind", id: 2 },
];

export default function Home() {
  return (
    <div className="container mx-auto px-10 mb-8 ">
      <Head>
        <title>CMS BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 ">
        <div className="col-span-8 col-span-1">
          {" "}
          {posts.map((post, index) => (
            <div key={post.id}>
              {post.id}
              {post.title}
              {post.excerpt}
            </div>
          ))}{" "}
        </div>

        <div className="lg:col-span-4 col-span-1">
          <div className="lg:sticky relative top-8"></div>
        </div>
      </div>
    </div>
  );
}
